import { useEffect, useState } from "react";

export default function ReportsPage() {
  const [reportText, setReportText] = useState("");
  const [intelJson, setIntelJson] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function loadReport() {
      setLoading(true);
      try {
        const res = await fetch("/api/intelligence/agent/explain-gemini");
        if (res.ok) {
          const data = await res.json();
          setReportText(data.report);
          setIntelJson(data.intelligence_json);
        }
      } catch (err) {
        console.error("Failed to load Gemini Executive Report:", err);
      } finally {
        setLoading(false);
      }
    }
    loadReport();
  }, []);

  function downloadPdf() {
    window.open("/api/intelligence/agent/report/pdf", "_blank");
  }

  return (
    <div className="page animate-in" style={{ paddingBottom: 40 }}>
      <header className="page-header" style={{ display: "flex", justifyContent: "space-between", alignItems: "center", flexWrap: "wrap", gap: 16 }}>
        <div>
          <h1 style={{ fontSize: "1.8rem", fontWeight: 800 }}>📄 Municipal Executive Reports & PDF Export</h1>
          <p>Grounded Environmental Reports generated by Gemini AI Analyst from Structured Intelligence JSON.</p>
        </div>
        <button className="btn btn-primary" onClick={downloadPdf} style={{ display: "flex", alignItems: "center", gap: 8 }}>
          📥 Download Official PDF Report
        </button>
      </header>

      {loading ? (
        <div className="loading-state">
          <div className="spinner"></div>
          <p>Generating Grounded Executive Environmental Report via Gemini Analyst...</p>
        </div>
      ) : (
        <div style={{ display: "grid", gridTemplateColumns: "2fr 1fr", gap: 24 }} className="forecast-grid">
          {/* Main Formatted Report View */}
          <div className="card" style={{ padding: 28 }}>
            <div style={{ whiteSpace: "pre-wrap", fontFamily: "sans-serif", lineHeight: 1.6, fontSize: "0.92rem", color: "var(--text-main)" }}>
              {reportText}
            </div>
          </div>

          {/* Side Inspection & Evidence Box */}
          <div style={{ display: "flex", flexDirection: "column", gap: 18 }}>
            <div className="card" style={{ padding: 20 }}>
              <h3 style={{ fontSize: "1rem", fontWeight: 700, marginBottom: 12 }}>🛡️ Verified Evidence JSON</h3>
              <div style={{ fontSize: "0.8rem", color: "var(--text-muted)", marginBottom: 8 }}>
                Confidence Score: <strong style={{ color: "var(--accent)" }}>{intelJson?.confidence}%</strong>
              </div>
              <div style={{ fontSize: "0.8rem", color: "var(--text-muted)", marginBottom: 8 }}>
                Environment Danger Index: <strong style={{ color: "#ff3d00" }}>{intelJson?.environmental_risk?.environmental_danger_score} / 100</strong>
              </div>
              <div style={{ fontSize: "0.8rem", color: "var(--text-muted)" }}>
                Alert Level: <strong style={{ color: "#ff9100" }}>{intelJson?.environmental_risk?.alert_level}</strong>
              </div>
            </div>

            <div className="card" style={{ padding: 20 }}>
              <h3 style={{ fontSize: "1rem", fontWeight: 700, marginBottom: 12 }}>🚨 Priority Inspection Wards</h3>
              {intelJson?.priority_inspection_wards?.map((w, idx) => (
                <div key={idx} style={{ padding: 10, borderRadius: 8, background: "rgba(255,255,255,0.03)", marginBottom: 8, fontSize: "0.8rem" }}>
                  <strong style={{ color: "var(--accent)" }}>{w.ward_id}</strong> (AQI {w.cluster_mean_aqi})
                  <div style={{ color: "var(--text-muted)", fontSize: "0.75rem", marginTop: 2 }}>{w.primary_reason}</div>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
